import { useEffect, useState } from 'react';
import { api } from '../lib/api';
export default function Sinkronisasi(){
  const [history,setHistory]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null);
  async function load(){ setHistory(await api('/api/sync/history')); }
  useEffect(()=>{load()},[]);
  async function open(id:string){ setSelected(await api('/api/sync/'+id)); }
  return <div className="space-y-4"><h1 className="text-xl font-bold">Sinkronisasi</h1>
    <div className="bg-slate-900 text-slate-100 p-3 rounded-lg text-xs font-mono">LOCAL DB ? COMPARE ? REMOTE ? DIFF ENGINE ? CONFLICT DETECTION ? USER CONFIRMATION ? SYNC</div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
      <div className="bg-white dark:bg-slate-800 rounded-xl border overflow-hidden"><div className="p-3 font-semibold border-b">Riwayat Sinkronisasi</div><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-2 text-left">Tanggal</th><th className="p-2">Jenis</th><th className="p-2">Status</th><th className="p-2">Aksi</th></tr></thead><tbody>{history.map((h:any)=><tr key={h.id} className="border-t"><td className="p-2">{new Date(h.startedAt).toLocaleString()}</td><td className="p-2">{h.type}</td><td className="p-2"><span className={"px-2 py-1 rounded text-xs "+(h.status==='SUCCESS'?"bg-emerald-100 text-emerald-700":h.status==='FAILED'?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700")}>{h.status}</span></td><td className="p-2"><button onClick={()=>open(h.id)} className="text-blue-600 hover:underline">Detail</button></td></tr>)}{history.length===0 && <tr><td colSpan={4} className="p-6 text-center text-slate-500">Belum ada riwayat. Lakukan Tarik Data di Dapodik Center.</td></tr>}</tbody></table></div>
      <div className="bg-white dark:bg-slate-800 rounded-xl border p-4"><div className="font-semibold mb-2">Detail Session</div>{selected ? <div className="space-y-2 text-sm"><div>Total: {selected.totalRecords} • Baru: {selected.newRecords} • Konflik: {selected.conflictCount} • Error: {selected.errorCount}</div><div className="max-h-64 overflow-auto text-xs border rounded"><table className="w-full"><thead><tr><th className="p-2 text-left">Entity</th><th className="p-2">Action</th></tr></thead><tbody>{selected.records?.map((r:any)=><tr key={r.id} className="border-t"><td className="p-2">{r.entityId||r.entity}</td><td className="p-2"><span className={"px-2 py-0.5 rounded "+(r.action==='NEW'?"bg-emerald-100":r.action==='CONFLICT'?"bg-amber-100":"bg-slate-100")}>{r.action}</span></td></tr>)}</tbody></table></div>{selected.conflicts?.length>0 && <div><h4 className="font-semibold mt-3">Konflik — pilih resolusi</h4>{selected.conflicts.map((c:any)=><div key={c.id} className="border p-2 rounded text-xs mt-1"><div>{c.entity} {c.entityId} — field <b>{c.field}</b></div><div>Lokal: {c.localValue} vs Dapodik: {c.remoteValue}</div><div className="flex gap-1 mt-1"><button className="px-2 py-1 bg-slate-800 text-white rounded">Gunakan Lokal</button><button className="px-2 py-1 bg-blue-600 text-white rounded">Gunakan Dapodik</button><button className="px-2 py-1 border rounded">Gabungkan</button><button className="px-2 py-1 border rounded">Lewati</button></div></div>)}</div>}</div> : <div className="text-slate-500 text-sm">Pilih session di kiri untuk melihat detail & resolusi konflik.</div>}</div>
    </div></div>;
}
